version: "3.9"

services:
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 6401Bernie
      MYSQL_DATABASE: myDB
      MYSQL_USER: sbk
      MYSQL_PASSWORD: taadtaad
    hostname: demopadns.sbkblog.online
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./:/var/www/html
    ports:
      - 5000:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: sbk
      WORDPRESS_DB_PASSWORD: taadtaad
      WORDPRESS_DB_NAME: myDB
    hostname: demopadns.sbkblog.online
volumes:
  db_data: {}